### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ujscjj** [aispeech-lab/WASE#1] opened 2021-10-29 08:51 UTC
Hi, it is a great job. Could you please update your codes? Thank you very much.

**Comment by haoyz** [comment] 2021-11-01 13:46
Thx. For some reasons, we will open source in December. Please forgive us.

**Comment by haoyz** [comment] 2021-11-01 13:47
Thx. For some reasons, we will open source in December. Please forgive us.
Duplicate of #

**Comment by haoyz** [comment] 2021-11-01 13:47
> Hi, it is a great job. Could you please update your codes? Thank you very much.

Thx. For some reasons, we will open source in December. Please forgive us.

**Closed as completed** 2021-11-01 13:51 UTC

**Comment by haoyz** [comment] 2022-01-11 13:40
Hi, the code is available in aispeech-lab/WASE_202112.

> Hi, it is a great job. Could you please update your codes? Thank you very much.
